---
- 'Feature:Embedding':
    - 'src/plugins/embeddable/**/*.*'
    - 'src/plugins/dashboard_embeddable_container/**/*.*'
- 'Feature:Drilldowns':
    - 'x-pack/plugins/drilldowns/**/*.*'
    - 'x-pack/plugins/dashboard_enhanced/public/services/drilldowns/**/*.*'
- 'Feature:ExpressionLanguage':
    - 'src/plugins/expressions/**/*.*'
    - 'src/plugins/bfetch/**/*.*'
- 'Team:apm':
    - 'x-pack/plugins/observability_solution/apm/**/*.*'
    - 'x-pack/test/apm_api_integration/**/*.*'
    - 'packages/kbn-apm-synthtrace/**/*.*'
    - 'packages/kbn-apm-synthtrace-client/**/*.*'
    - 'packages/kbn-apm-utils/**/*.*'
- 'Team:Fleet':
    - 'x-pack/plugins/fleet/**/*.*'
    - 'x-pack/test/fleet_api_integration/**/*.*'
- 'Team:uptime':
    - 'x-pack/plugins/observability_solution/synthetics/**/*.*'
    - 'x-pack/plugins/observability_solution/ux/**/*.*'
    - 'x-pack/plugins/observability_solution/observability/public/components/shared/exploratory_view/**/*.*'
